"""Handler package — re-exports all handler functions needed by bot.py."""

from .brainstorm import (
    cancel_brainstorming,
    finish_brainstorming,
    handle_brainstorm_action,
    handle_brainstorm_hint_button,
    handle_brainstorm_message,
    handle_brainstorm_prompt,
    show_brainstorm_history,
    start_brainstorming,
)
from .common import (
    State,
    _brainstorm_hint_keyboard,
    _brainstorm_hint_long_keyboard,
    _cancel_keyboard,
    _is_brainstorm_error,
    _nav_keyboard,
    authorized,
    authorized_callback,
    cancel,
    get_user_data,
    handle_input_cancel,
    help_command,
    reply_text,
    user_data_store,
)
from .jobs import (
    _format_completion_summary,
    check_task_completion,
    check_task_progress,
    handle_completion_diff,
    run_log_rotation,
)
from .projects import (
    handle_clone_url,
    handle_github_choice,
    handle_name,
    handle_page_navigation,
    handle_project_name,
    project_selected,
    show_project_menu,
    show_projects,
    start,
)
from .tasks import (
    handle_cancel_queue,
    handle_custom_iterations,
    handle_idea,
    handle_idea_button,
    handle_iterations,
    show_iterations_menu,
    show_queue,
    show_status,
    skip_idea,
    start_task,
)

__all__ = [
    # common
    "State",
    "authorized",
    "authorized_callback",
    "cancel",
    "get_user_data",
    "handle_input_cancel",
    "help_command",
    "reply_text",
    "user_data_store",
    "_brainstorm_hint_keyboard",
    "_brainstorm_hint_long_keyboard",
    "_cancel_keyboard",
    "_is_brainstorm_error",
    "_nav_keyboard",
    # projects
    "handle_clone_url",
    "handle_github_choice",
    "handle_name",
    "handle_page_navigation",
    "handle_project_name",
    "project_selected",
    "show_project_menu",
    "show_projects",
    "start",
    # tasks
    "handle_cancel_queue",
    "handle_custom_iterations",
    "handle_idea",
    "handle_idea_button",
    "handle_iterations",
    "show_iterations_menu",
    "show_queue",
    "show_status",
    "skip_idea",
    "start_task",
    # brainstorm
    "cancel_brainstorming",
    "finish_brainstorming",
    "handle_brainstorm_action",
    "handle_brainstorm_hint_button",
    "handle_brainstorm_message",
    "handle_brainstorm_prompt",
    "show_brainstorm_history",
    "start_brainstorming",
    # jobs
    "_format_completion_summary",
    "check_task_completion",
    "check_task_progress",
    "handle_completion_diff",
    "run_log_rotation",
]
